### ISSUE TITLE
Add install script

### ISSUE THREAD

**Issue by cdthomp1** [cdthomp1/mongo-express-node-template#10]
Make this an npm script(s) to allow for easy installation (similar to npx create-react-app). The basic command `npx create-men-template` that installs the basic template with the Ejs view engine. Additional flags, like `--react` for example may be added to allow for additional frameworks or tools to be added.

**Comment by cdthomp1** [comment]
I updated this issue to be only the base install script, `npx create-men-tempalte` with the idea of having other issues for the other framework scripts.

Happy Hacking! 😃

**Comment by HaiderSultanArc** [comment]
Hey, I want to work on this issue. I have modified the code that I will be pushing in a few minutes. You can check it and merge it into the project.
So now npx create-mern-template will create the template using ejs-template provided in the template folder.
For creating a react project the command will require a flag --react with create-mern-template. So, we can npx create-mern-template --react to create react app client-side.
